name: Scrape latest data

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '42 18 * * *'
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Fetch latest data
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |-
        go run main.go OoTRandomizer/OoT-Randomizer
    - name: Commit and push if it changed
      run: |-
        git config user.name "github bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Data update: ${timestamp}" || exit 0
        git push
